### PR TITLE
Document validator

### PR DESCRIPTION
**Pull request by Siegrift**
https://api3dao.atlassian.net/browse/AN-608
and
https://api3dao.atlassian.net/browse/AN-609

The documentation are separated into two commits for better visibility.

### CODE REVIEW

**Comment by Siegrift** [comment]
I've tested the documentation code snippets and examples by publishing locally to verdaccio.

**Review by wkande — COMMENTED** [review]
This seems to be easier to use now. Let me know when it is ready to merge, thanks.

**Comment by Siegrift** [comment]
@wkande It's ready to review and merge

**Comment by wkande** [comment]
This is great as it now is simple to use and understand. I would like to return to it in the next few days with just a very minor change if that is OK.

**Pull request merged**
