### PR TITLE
Post-processing docs

### PR DESCRIPTION
**Pull request by bbenligiray**

### CODE REVIEW

**Comment by wkande** [comment]
I went ahead with the merge. I wanted to add these into the Specifications group to see how they will fit with my new heartbeat.md and http-gateway.md docs. Hoping they make sense to co-exist together.

**Comment by bbenligiray** [comment]
I was planning to work on this outside the repo, then @Siegrift asked me to create a PR https://api3workspace.slack.com/archives/C02AYRX8D89/p1631028174018000?thread_ts=1630936074.005200&cid=C02AYRX8D89 so I did, but it was a draft PR because this is nowhere near done. So this needs to be unmerged because it will not have been implemented in the next version.

**Comment by wkande** [comment]
OK just to be clear you want me to "revert" this pull request?

**Comment by bbenligiray** [comment]
Yes, but let's keep the `post-processing` branch for reference

**Pull request merged**
