### PR TITLE
Prettier enforce

### PR DESCRIPTION
**Pull request by Siegrift**
* Added pre-push hook enforcing the prettier format
* Added CI format check
* Added all remaining files to prettierignore

### CODE REVIEW

**Review by wkande — CHANGES_REQUESTED** [review]
I want to start with the `/.prettierignore` file that I had merged today. Yours will be more restrictive. Can we delete that file from this PR? In that there is a conflict it might make things easier as well.

**Comment by Siegrift** [comment]
I needed to add couple more files in order for the formatter checks to pass - but I've just appended those files to the prettierignore you have used.

**Comment by wkande** [comment]
This is the .prettierignore file contents I had applied. Not sure what your's is?
```
/.git
/.github
/.vscode
/node_modules
/archived
/docs/airnode/pre-alpha

# .vuepress
/docs/.vuepress/components
/docs/.vuepress/dist
/docs/.vuepress/public
/docs/.vuepress/styles

# dao-members
/docs/dao-members/assets
/docs/dao-members/figures

# api3
/docs/api3/assets

# v0.2
/docs/airnode/v0.2/assets
/docs/airnode/v0.2/figures

# common

```

**Comment by wkande** [comment]
@Siegrift Not sure where to go from here. I have formatted the dao-dashboard docs but do not want to format things like `/pre-alpha`,  Vue components, styles,  until v0.3. Looks like your `.prettierignore` file will force formatting on them. I need more time to valid them. I was hoping to get the force working on the markdown files that I have validated now.

**Comment by Siegrift** [comment]
I've changed all the files with CRLF ending to LF. 
All of the diffs that were created by this are basically identical files.

**Pull request merged**
