### PR TITLE
Add string32 and bool options to Airnode ABI

### PR DESCRIPTION
**Pull request by Siegrift**
https://api3dao.atlassian.net/browse/AN-459

### CODE REVIEW

**Review by wkande — APPROVED** [review]
Everything seems to match task JIRA AN-459 best I can tell. Someone better than me probably could do a better review but in the end you seem to get it right every time so let's merge this.

**Comment by Siegrift** [comment]
We can maybe wait till the PR in Airnode is merged. We iterated multiple times already on the design of this, but I am hopeful this is gonna be the final version.

**Comment by dcroote** [comment]
@Siegrift - as an aside it looks like the branch deployment workflow didn't run because the workflow file isn't present- did you pull from `main` before branching?

**Comment by Siegrift** [comment]
Not sure, but we should setup "require branches to be up to date" in github settings, so that you have to rebase to latest main.

**Pull request merged**
