### PR TITLE
Add heartbeat payload signature

### LINKED ISSUE #994: Heartbeat payload signing
Documentation for https://github.com/api3dao/airnode/issues/1337

### PR DESCRIPTION
**Pull request by vponline**
Closes #994

### CODE REVIEW

**Comment by vponline** [comment]
Converted to draft as it was decided that this will not be part of `v0.9`

**Comment by vponline** [comment]
Moved changes to `v0.10` so this can be reviewed and merged now

**Review by wkande — APPROVED** [review]
This looks right. The oddest thing, I had done a pull against my man branch after your previous merge and the heartbeatIDs removed for this PR were already gone. But it does not appear to matter. So we are good.

**Comment by wkande** [comment]
Even though 8 files were changed here only 1 files `docs/airnode/v0.10/grp-providers/guides/build-an-airnode/heartbeat.md` came done to my local repo with `git pull`. Seems the previous PR had already change the previous 7?

@vponline - After I reploy your changes to docs.api3.org, could you take a look at these changes to verify they are all there? Seems like it to me.

**Comment by vponline** [comment]
> Even though 8 files were changed here only 1 files `docs/airnode/v0.10/grp-providers/guides/build-an-airnode/heartbeat.md` came done to my local repo with `git pull`. Seems the previous PR had already change the previous 7?
> 
> @vponline - After I reploy your changes to docs.api3.org, could you take a look at these changes to verify they are all there? Seems like it to me.

That is indeed strange. I checked the v0.10 docs.api3.org and it looks like these changes are on there correctly as well.

**Pull request merged**
