### PR TITLE
Add descriptions to landing page buttons

### PR DESCRIPTION
**Pull request by dcroote**
Adds images and descriptive text on the landing page for users unfamiliar with the project.

### CODE REVIEW

**Comment by wkande** [comment]
Changing the DocumentSetButtons Vue component should be simple enough. When adding styles to the file use longer names like doc-set-btns-text. I discovered the css can have impact on other components if they use the same name.
```
 doc-set-btns-text{
   ...
}
```

We should probably change the existing style from `btn` to `doc-set-btn` as well.

**Comment by dcroote** [comment]
@wkande - have a look now, I've added images and improved the text descriptions, being mindful of both desktop and mobile

**Comment by wkande** [comment]
@dcroote - Can the router-link wrap the image and description while keeping the heading font green and the paragraph font black? This makes it easier for the reader to select a document set.

Also can we center the button and heading above the paragraph. It might look better though that remains to be seen.

**Comment by dcroote** [comment]
@wkande  - I centered the doc sets, including the descriptive text (it looked funny at some screen widths not being centered along with the image and header link).

I also made the images clickable. I didn't make the descriptive text itself clickable as I think that would be a bit unexpected and probably lead to accidental clicks, especially when scrolling on mobile.

To see the updated site you made have to do a hard refresh to clear the cache.

**Comment by wkande** [comment]
Now I'm just getting picky. The icons seem so black and gloomy. What do you think about adding `opacity: .7` or so to lighten them up? Also the "OIS" Link is getting pushed down by its non-standard fixed icon. Can the "OIS" be moved up: `margin-top:-7px` or so? That way all the doc set names line up on the desktop browser. And maybe some periods in the description. Seems funny without them when the blocks below have them.

**Comment by dcroote** [comment]
All good suggestions! I avoided playing with the margin for the OIS image by instead setting all img heights to be fixed rather than width

**Review by wkande — APPROVED** [review]
Look clean

**Pull request merged**
