### PR TITLE
Add why use airnode docs page

### PR DESCRIPTION
**Pull request by Siegrift**
This is a page I (subjectively) had in mind and was missing.

I realize this is subjective (and I am not a particularly experienced writer) so I'd like feedback and proofread.
Any thoughts what could be added?

### CODE REVIEW

**Comment by wkande** [comment]
@Siegrift  So I like the **pros** list. The doc overall quickly answers it own question "Why use Airnode?" Not so sure about the **cons**. This doc will be one of the very first that new users will read. Its very title will draw them in. From a marketing perspective the cons could have a negative impact. Should we comment out the **cons** and see if later they might be better discussed somewhere else?

**Comment by Siegrift** [comment]
> Should we comment out the cons and see if later they might be better discussed somewhere else?

Nope, it should get discussed here and now. If it's something we don't want to have I'll remove it.

**Comment by wkande** [comment]
OK why don't we go with it and get input (or see what the reactions are). I might go back and try and candy coat them a little.

**Comment by Siegrift** [comment]
Yeah, there are assigned as reviewers on the PR, so they already received a notification :)

**Review by amarthadan — COMMENTED** [review]
I personally quite like when some software documentation has a cons section. It feels more like they know what they're doing, these are the compromises that needed to be made and they're giving you all the information. So, I'm for keeping that section even without any sugarcoating, but if you think it's necessary I'm ok with that.

**Review by wkande — APPROVED** [review]
I can live with this.

**Comment by dcroote** [comment]
@Siegrift  - I've updated the language, softening parts but remaining fair and retaining the key messages elsewhere. There ended up being enough edits that suggesting changes through github wasn't productive so I pushed directly.

**Comment by Siegrift** [comment]
I agree this is much better. I'm merging.

**Pull request merged**
