### PR TITLE
feat: describe new _minConfirmations reserved parameter

### LINKED ISSUE #1130: Add a new reserved parameter to allow minConfirmations to be specified
Documentation for https://github.com/api3dao/airnode/issues/1393
One of the TODOs from the Migration guide should be part of this issue (https://github.com/api3dao/api3-docs/pull/1174#issuecomment-1406386840)

### PR DESCRIPTION
**Pull request by dcroote**
Closes #1130

### CODE REVIEW

**Comment by wkande** [comment]
Somewhere between `v0.9` and `v0.10` the sentence below (strikethrough) was removed for. I see it is also gone from this PR. Is this intended? The content below is from `v0.9`, of course there are now 4 reserved parameters available for `v0.10`.

> The current list of reserved parameters are `_type`, `_path` and `_times`. See [Reserved Parameters](/reference/ois/latest/reserved-parameters.md) in the OIS document set to understand what each of these parameters are for. In most cases, all three should be defined as reserved parameters with no fixed/default values, as doing so provides the requester with the most flexibility. ~~In most cases, all three should be defined as reserved parameters with no fixed/default values, as doing so provides the requester with the most flexibility.~~

**Comment by dcroote** [comment]
I removed that sentence because otherwise users would be effectively allowed to call any endpoint (through an arbitrary `_path`) and need to know the what type of response it returns and if numerical, what to multiply it by. We don't have those 3 reserved parameters empty in an tutorial, example, etc.

This PR will make 5 reserved parameters. 

Converted to draft because the request ordering logic needs to change.

**Comment by wkande** [comment]
I have migrated this PR to the point that Derek will make new changes mentioned above.

**Comment by wkande** [comment]
@dcroote I see this was changed back to Open from Draft. Can I merge it?

**Comment by dcroote** [comment]
Yes and same with the corresponding Vitepress PR

**Pull request merged**
