### PR TITLE
Add authorizer type to config.json for v0.8

### LINKED ISSUE #842: Add hardcoded whitelisting into the config file
Documentation for https://github.com/api3dao/airnode/issues/1197

### LINKED ISSUE #843: Require authorizer types to be specified
Documentation for https://github.com/api3dao/airnode/issues/1196

### PR DESCRIPTION
**Pull request by vponline**
This adds `authorizer` types to `config.json`.

For this issue: #843 and PR: [1291](https://github.com/api3dao/airnode/pull/1291)

### CODE REVIEW

**Review by wkande — APPROVED** [review]
Is there more than one type  of `chains.authorizers.[authorizerType]`? Assuming the following is a type of `authorizerType`.

- requesterEndpointAuthorizers:[]

**Comment by vponline** [comment]
> Is there more than one type of `chains.authorizers.[authorizerType]`? Assuming the following is a type of `authorizerType`.
> * requesterEndpointAuthorizers:[]

That seems to be the idea, but in the short term (v0/v1) it will be only `requesterEndpointAuthorizers`.

**Comment by vponline** [comment]
Converted this to draft as we may be delaying this change for now. ([slack](https://api3workspace.slack.com/archives/C02AYRX8D89/p1656417246277959?thread_ts=1656334347.924069&cid=C02AYRX8D89))

**Comment by vponline** [comment]
I've added the new `authorizations` field and converted this back for review. I put this into the same PR as it is related to the `authorizer` changes that I thought it would be easier to review.

The use case of the new `authorizations` config field is to list authorized requester addresses for a specific `endpointId` and type of authorizer. If these are present in the config, the Airnode will skip the on-chain authorization check for that specific request.

@wkande You may be more familiar with the authorizer functionality than me so please have a look when you have a chance and let me know if these documentation additions are not enough and I'll be happy to fix where necessary.

**Review by wkande — APPROVED** [review]
This looks complete but I do not entirely understand it. I will merge this today but will seek help on understanding it better. Creating a new issue to follow through on this.

**Pull request merged**
