### PR TITLE
Remove unused `ois.[0].apiSpecifications.security` field

### PR DESCRIPTION
**Pull request by amarthadan**
This was already removed in https://github.com/api3dao/api3-docs/commit/e874b2795c69a6845b0dfe00c59ec003b6072f08, not sure why it came back :smile:

### CODE REVIEW

**Comment by wkande** [comment]
@amarthadan I had just added the security field back in because Jakub told me it needs to be there.

**Comment by amarthadan** [comment]
> @amarthadan I had just added the security field back in because Jakub told me it needs to be there.

That must have been some miscommunication. I've checked and it's not used anywhere in the code so it really shouldn't be there.

**Comment by drgy** [comment]
I think there was a misunderstanding, the `security` was missing in one list in the docs, I assumed it was supposed to be there, as the `security` parameter was described on multiple places in the docs, I have no idea what the node itself needs to run correctly.

**Comment by wkande** [comment]
Sounds good then. I will merge this and double check it to be sure it is gone completely, Thanks

**Pull request merged**
