### PR TITLE
Fix temporary 404 before redirect when accessing latest docs

### LINKED ISSUE #826: Fix page flickering for the docs redirect
When one accesses the https://docs.api3.org/airnode/ URL to access the latest docs there's a brief flicker showing the 404 page before redirecting.

### PR DESCRIPTION
**Pull request by Siegrift**
Closes: https://github.com/api3dao/api3-docs/issues/826

See: https://vuepress-community.netlify.app/en/plugins/dehydrate/#why-we-need-this-plugin

### CODE REVIEW

**Review by amarthadan — APPROVED** [review]
Works for me :+1:

**Comment by wkande** [comment]
@Siegrift So how does this bad boy work? Seems to work good.

**Comment by Siegrift** [comment]
> So how does this bad boy work? Seems to work good.

I think this applies to our case: https://vuepress-community.netlify.app/en/plugins/dehydrate/#using-pure-html. Basically, I think the plugin prevents Vue to render the 404. I am not sure if the issue will fix the CI workaround by @dcroote , but I am looking forward to test it.

Feel free to merge this and please release a new version of docs so I (or someone else) can start looking at https://github.com/api3dao/airnode/issues/1293.

**Comment by wkande** [comment]
OK will merge now and publish.

**Pull request merged**
